# basic options
title: CSE2020 음악프로그래밍
author: 도경구
email: doh@hanyang.ac.kr
description: 한양대학교 ERICA 소프트웨어융합대학 소프트웨어학부
twitter_username:
github_username: Doggzone

# Build settings
markdown: kramdown
theme: minima
